export enum SignCategory {
  Nature = 'Nature',
  Emotions = 'Emotions',
  Actions = 'Actions',
  Objects = 'Objects',
  Greetings = 'Greetings',
  Other = 'Other'
}

// --- Custom Categories Support ---
const CUSTOM_CATEGORIES_KEY = 'signmoji_custom_categories';

export const DEFAULT_CATEGORIES: string[] = Object.values(SignCategory);

export function getCustomCategories(): string[] {
  try {
    const stored = localStorage.getItem(CUSTOM_CATEGORIES_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch { return []; }
}

export function getAllCategories(): string[] {
  const custom = getCustomCategories();
  return [...DEFAULT_CATEGORIES, ...custom.filter(c => !DEFAULT_CATEGORIES.includes(c))];
}

export function addCustomCategory(name: string): string[] {
  const trimmed = name.trim();
  if (!trimmed) return getAllCategories();
  const all = getAllCategories();
  if (all.some(c => c.toLowerCase() === trimmed.toLowerCase())) return all;
  const custom = getCustomCategories();
  custom.push(trimmed);
  localStorage.setItem(CUSTOM_CATEGORIES_KEY, JSON.stringify(custom));
  return getAllCategories();
}

export function removeCustomCategory(name: string): string[] {
  const custom = getCustomCategories().filter(c => c !== name);
  localStorage.setItem(CUSTOM_CATEGORIES_KEY, JSON.stringify(custom));
  return getAllCategories();
}

export type SignLanguage = 'ASL' | 'PSL' | 'BSL' | 'Other';

export interface SignEmoji {
  id: string;
  name: string;
  videoUrl: string; // Blob URL or uploaded URL or data URL
  videoBlob?: Blob; // Store original recording blob for upload
  literalIconUrl: string; // Generated by Gemini or from Assets
  category: SignCategory;
  createdAt: number;
  language?: SignLanguage;
  videoTransform?: { x: number; y: number; scale: number };
}

export interface Asset {
  id: string;
  url: string;
  name: string;
  type: 'image' | 'icon';
  createdAt?: number;
}

export type InputMode = 'upload' | 'camera' | 'screen' | 'link' | 'search';

export interface CreatorState {
  step: 'input-selection' | 'recording' | 'search' | 'preview' | 'processing' | 'complete';
  videoBlob: Blob | null;
  videoUrl: string | null;
  signName: string;
  category: SignCategory;
}